[package]
name = "horaire"
version = "0.2.0"
authors = ["Christian FOUCHER <christian.foucher@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
select = "0.4"
error-chain = "0.12"

serde="1.0"
serde_json="1.0"
serde_derive="1.0"

chrono = "0.4"
